### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by alexthelion** [awerlang/observable-profiler#1]
Hi, 
I'm trying to use the angular bootstrap example, I defined it in the main.ts file:

`import {enableProdMode} from '@angular/core';
import {platformBrowserDynamic} from '@angular/platform-browser-dynamic';

import {AppModule} from './app/app.module';
import {environment} from './environments/environment';
import {Observable} from 'rxjs';
import {setup, track, printSubscribers} from 'observable-profiler';

setup(Observable);

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule).then(ref => {
  track();
  window.stopProfiler = () => {
    ref.destroy();
    const subscribers = track(false);
    printSubscribers({
      subscribers,
    });
  };
}).catch(err => console.error(err));
`
But there is a compilation error:

>     ERROR in src/main.ts(17,10): error TS2339: Property 'stopProfiler' does not exist on type 'Window'.

**Comment by awerlang** [comment]
Hello, thanks for the report.

There's an error in the snippet, given the `window` object doesn't expose that method.

One way to fix the error is casting to any type like this:

```
(window as any).stopProfiler = ...
```

**Comment by alexthelion** [comment]
The profiler is not working for me, there isn't any nested subscriptions.
![image](https://user-images.githubusercontent.com/6614196/62830340-f9099280-bc15-11e9-8178-5d50ecff09fd.png)

**Comment by awerlang** [comment]
Hello, since you're using the angular bootstrap recipe, I assume you're using default settings. To report indirect/nested subscriptions as well, you need to pass another parameter:

```
printSubscribers({
    subscribers,
    reportInnerSubscriptions: true,
});
```

There are additional parameters to this method which aren't properly documented (yet, PRs welcome) in README. They're documented in tsdoc though and should be available through IntelliSense.

**Comment by alexthelion** [comment]
Hello, 
I tried that and still there are errors.
I changed to angular recipe, and still I got errors, maybe it's not working with ngrx?
Here is my code: 
`import {Component} from '@angular/core';
import { Observable } from 'rxjs';
import { setup, track, printSubscribers } from 'observable-profiler';
import {environment} from '../environments/environment';

if (!environment.production) {
  setup(Observable);
}
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'ngrx-demo';

  constructor() {
  }


  onActivate() {
    track();
  }

  onDeactivate(component: object) {
    const subscribers = track(false);
    printSubscribers({
      subscribers,
      reportInnerSubscriptions: true,
      prefix: component.constructor.name,
      timeout: 200,
    });
  }
}
`

And here is the errors:
`A bad HTTP response code (404) was received when fetching the script.
index.js:113 TodosComponent Current subscriptions (including indirect/nested): 36
(anonymous) @ index.js:113
fulfilled @ index.js:3
invoke @ zone-evergreen.js:359
onInvoke @ core.js:34201
invoke @ zone-evergreen.js:358
run @ zone-evergreen.js:124
(anonymous) @ zone-evergreen.js:855
invokeTask @ zone-evergreen.js:391
onInvokeTask @ core.js:34182
invokeTask @ zone-evergreen.js:390
runTask @ zone-evergreen.js:168
drainMicroTaskQueue @ zone-evergreen.js:559
invokeTask @ zone-evergreen.js:469
ZoneTask.invoke @ zone-evergreen.js:454
timer @ zone-evergreen.js:2650
setTimeout (async)
scheduleTask @ zone-evergreen.js:2671
scheduleTask @ zone-evergreen.js:378
onScheduleTask @ zone-evergreen.js:272
scheduleTask @ zone-evergreen.js:372
scheduleTask @ zone-evergreen.js:211
scheduleMacroTask @ zone-evergreen.js:234
scheduleMacroTaskWithCurrentZone @ zone-evergreen.js:1107
(anonymous) @ zone-evergreen.js:2686
proto.<computed> @ zone-evergreen.js:1428
(anonymous) @ index.js:93
ZoneAwarePromise @ zone-evergreen.js:876
delay @ index.js:92
(anonymous) @ index.js:108
(anonymous) @ index.js:6
ZoneAwarePromise @ zone-evergreen.js:876
push../node_modules/observable-profiler/dist/_esm2015/index.js.__awaiter @ index.js:2
printSubscribers @ index.js:106
onDeactivate @ app.component.ts:27
(anonymous) @ AppComponent.html:2
handleEvent @ core.js:38098
callWithDebugContext @ core.js:39716
debugHandleEvent @ core.js:39352
dispatchEvent @ core.js:25818
(anonymous) @ core.js:27715
schedulerFn @ core.js:31094
__tryOrUnsub @ Subscriber.js:185
next @ Subscriber.js:124
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:31013
deactivate @ router.js:7214
deactivateRouteAndOutlet @ router.js:3071
deactivateRouteAndItsChildren @ router.js:3029
deactivateRoutes @ router.js:3014
(anonymous) @ router.js:2971
deactivateChildRoutes @ router.js:2964
activate @ router.js:2948
(anonymous) @ router.js:2923
_next @ map.js:29
next @ Subscriber.js:49
_next @ tap.js:46
next @ Subscriber.js:49
_next @ map.js:35
next @ Subscriber.js:49
notifyNext @ switchMap.js:67
_next @ InnerSubscriber.js:11
next @ Subscriber.js:49
_next @ map.js:35
next @ Subscriber.js:49
(anonymous) @ scalar.js:4
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
subscribe @ index.js:41
call @ map.js:16
subscribe @ Observable.js:23
subscribe @ index.js:41
(anonymous) @ subscribeTo.js:20
subscribeToResult @ subscribeToResult.js:7
_innerSub @ switchMap.js:46
_next @ switchMap.js:36
next @ Subscriber.js:49
notifyNext @ switchMap.js:67
_next @ InnerSubscriber.js:11
next @ Subscriber.js:49
_next @ map.js:35
next @ Subscriber.js:49
_next @ tap.js:46
next @ Subscriber.js:49
notifyNext @ mergeMap.js:69
_next @ InnerSubscriber.js:11
next @ Subscriber.js:49
_next @ map.js:35
next @ Subscriber.js:49
_complete @ takeLast.js:52
complete @ Subscriber.js:61
_complete @ Subscriber.js:79
complete @ Subscriber.js:61
_complete @ mergeMap.js:64
complete @ Subscriber.js:61
(anonymous) @ subscribeToArray.js:6
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
subscribe @ index.js:41
call @ mergeMap.js:21
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ scan.js:18
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ takeLast.js:22
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ map.js:16
subscribe @ Observable.js:23
subscribe @ index.js:41
(anonymous) @ subscribeTo.js:20
subscribeToResult @ subscribeToResult.js:7
_innerSub @ mergeMap.js:59
_tryNext @ mergeMap.js:53
_next @ mergeMap.js:36
next @ Subscriber.js:49
_next @ tap.js:46
next @ Subscriber.js:49
(anonymous) @ scalar.js:4
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
subscribe @ index.js:41
call @ tap.js:16
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ mergeMap.js:21
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ tap.js:16
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ map.js:16
subscribe @ Observable.js:23
subscribe @ index.js:41
(anonymous) @ subscribeTo.js:20
subscribeToResult @ subscribeToResult.js:7
_innerSub @ switchMap.js:46
_next @ switchMap.js:36
next @ Subscriber.js:49
_next @ filter.js:33
next @ Subscriber.js:49
_next @ tap.js:46
next @ Subscriber.js:49
_next @ tap.js:46
next @ Subscriber.js:49
notifyNext @ mergeMap.js:69
_next @ InnerSubscriber.js:11
next @ Subscriber.js:49
_next @ map.js:35
next @ Subscriber.js:49
notifyNext @ mergeMap.js:69
_next @ InnerSubscriber.js:11
next @ Subscriber.js:49
_complete @ defaultIfEmpty.js:25
complete @ Subscriber.js:61
_complete @ Subscriber.js:79
complete @ Subscriber.js:61
_complete @ Subscriber.js:79
complete @ Subscriber.js:61
_complete @ mergeMap.js:64
complete @ Subscriber.js:61
(anonymous) @ subscribeToArray.js:6
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
subscribe @ index.js:41
call @ mergeMap.js:21
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ filter.js:13
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ take.js:22
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ defaultIfEmpty.js:10
subscribe @ Observable.js:23
subscribe @ index.js:41
(anonymous) @ subscribeTo.js:20
subscribeToResult @ subscribeToResult.js:7
_innerSub @ mergeMap.js:59
_tryNext @ mergeMap.js:53
_next @ mergeMap.js:36
next @ Subscriber.js:49
_complete @ defaultIfEmpty.js:25
complete @ Subscriber.js:61
_complete @ Subscriber.js:79
complete @ Subscriber.js:61
_complete @ Subscriber.js:79
complete @ Subscriber.js:61
_complete @ mergeMap.js:64
complete @ Subscriber.js:61
(anonymous) @ subscribeToArray.js:6
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
subscribe @ index.js:41
call @ mergeMap.js:21
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ filter.js:13
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ take.js:22
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ defaultIfEmpty.js:10
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ mergeMap.js:21
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ map.js:16
subscribe @ Observable.js:23
subscribe @ index.js:41
(anonymous) @ subscribeTo.js:20
Show 185 more frames
index.js:124 TodosComponent #381: Error
    at ReplaySubject.subscribe (index.js:44)
    at Observable._subscribe (Observable.js:76)
    at Observable.subscribe (Observable.js:27)
    at Observable.subscribe (index.js:41)
    at MapOperator.call (map.js:16)
    at Observable.subscribe (Observable.js:23)
    at Observable.subscribe (index.js:41)
    at Store._subscribe (Observable.js:76)
    at Store.subscribe (Observable.js:27)
    at Store.subscribe (index.js:41)
(anonymous) @ index.js:124
(anonymous) @ index.js:115
fulfilled @ index.js:3
invoke @ zone-evergreen.js:359
onInvoke @ core.js:34201
invoke @ zone-evergreen.js:358
run @ zone-evergreen.js:124
(anonymous) @ zone-evergreen.js:855
invokeTask @ zone-evergreen.js:391
onInvokeTask @ core.js:34182
invokeTask @ zone-evergreen.js:390
runTask @ zone-evergreen.js:168
drainMicroTaskQueue @ zone-evergreen.js:559
invokeTask @ zone-evergreen.js:469
ZoneTask.invoke @ zone-evergreen.js:454
timer @ zone-evergreen.js:2650
setTimeout (async)
scheduleTask @ zone-evergreen.js:2671
scheduleTask @ zone-evergreen.js:378
onScheduleTask @ zone-evergreen.js:272
scheduleTask @ zone-evergreen.js:372
scheduleTask @ zone-evergreen.js:211
scheduleMacroTask @ zone-evergreen.js:234
scheduleMacroTaskWithCurrentZone @ zone-evergreen.js:1107
(anonymous) @ zone-evergreen.js:2686
proto.<computed> @ zone-evergreen.js:1428
(anonymous) @ index.js:93
ZoneAwarePromise @ zone-evergreen.js:876
delay @ index.js:92
(anonymous) @ index.js:108
(anonymous) @ index.js:6
ZoneAwarePromise @ zone-evergreen.js:876
push../node_modules/observable-profiler/dist/_esm2015/index.js.__awaiter @ index.js:2
printSubscribers @ index.js:106
onDeactivate @ app.component.ts:27
(anonymous) @ AppComponent.html:2
handleEvent @ core.js:38098
callWithDebugContext @ core.js:39716
debugHandleEvent @ core.js:39352
dispatchEvent @ core.js:25818
(anonymous) @ core.js:27715
schedulerFn @ core.js:31094
__tryOrUnsub @ Subscriber.js:185
next @ Subscriber.js:124
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:31013
deactivate @ router.js:7214
deactivateRouteAndOutlet @ router.js:3071
deactivateRouteAndItsChildren @ router.js:3029
deactivateRoutes @ router.js:3014
(anonymous) @ router.js:2971
deactivateChildRoutes @ router.js:2964
activate @ router.js:2948
(anonymous) @ router.js:2923
_next @ map.js:29
next @ Subscriber.js:49
_next @ tap.js:46
next @ Subscriber.js:49
_next @ map.js:35
next @ Subscriber.js:49
notifyNext @ switchMap.js:67
_next @ InnerSubscriber.js:11
next @ Subscriber.js:49
_next @ map.js:35
next @ Subscriber.js:49
(anonymous) @ scalar.js:4
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
subscribe @ index.js:41
call @ map.js:16
subscribe @ Observable.js:23
subscribe @ index.js:41
(anonymous) @ subscribeTo.js:20
subscribeToResult @ subscribeToResult.js:7
_innerSub @ switchMap.js:46
_next @ switchMap.js:36
next @ Subscriber.js:49
notifyNext @ switchMap.js:67
_next @ InnerSubscriber.js:11
next @ Subscriber.js:49
_next @ map.js:35
next @ Subscriber.js:49
_next @ tap.js:46
next @ Subscriber.js:49
notifyNext @ mergeMap.js:69
_next @ InnerSubscriber.js:11
next @ Subscriber.js:49
_next @ map.js:35
next @ Subscriber.js:49
_complete @ takeLast.js:52
complete @ Subscriber.js:61
_complete @ Subscriber.js:79
complete @ Subscriber.js:61
_complete @ mergeMap.js:64
complete @ Subscriber.js:61
(anonymous) @ subscribeToArray.js:6
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
subscribe @ index.js:41
call @ mergeMap.js:21
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ scan.js:18
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ takeLast.js:22
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ map.js:16
subscribe @ Observable.js:23
subscribe @ index.js:41
(anonymous) @ subscribeTo.js:20
subscribeToResult @ subscribeToResult.js:7
_innerSub @ mergeMap.js:59
_tryNext @ mergeMap.js:53
_next @ mergeMap.js:36
next @ Subscriber.js:49
_next @ tap.js:46
next @ Subscriber.js:49
(anonymous) @ scalar.js:4
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
subscribe @ index.js:41
call @ tap.js:16
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ mergeMap.js:21
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ tap.js:16
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ map.js:16
subscribe @ Observable.js:23
subscribe @ index.js:41
(anonymous) @ subscribeTo.js:20
subscribeToResult @ subscribeToResult.js:7
_innerSub @ switchMap.js:46
_next @ switchMap.js:36
next @ Subscriber.js:49
_next @ filter.js:33
next @ Subscriber.js:49
_next @ tap.js:46
next @ Subscriber.js:49
_next @ tap.js:46
next @ Subscriber.js:49
notifyNext @ mergeMap.js:69
_next @ InnerSubscriber.js:11
next @ Subscriber.js:49
_next @ map.js:35
next @ Subscriber.js:49
notifyNext @ mergeMap.js:69
_next @ InnerSubscriber.js:11
next @ Subscriber.js:49
_complete @ defaultIfEmpty.js:25
complete @ Subscriber.js:61
_complete @ Subscriber.js:79
complete @ Subscriber.js:61
_complete @ Subscriber.js:79
complete @ Subscriber.js:61
_complete @ mergeMap.js:64
complete @ Subscriber.js:61
(anonymous) @ subscribeToArray.js:6
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
subscribe @ index.js:41
call @ mergeMap.js:21
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ filter.js:13
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ take.js:22
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ defaultIfEmpty.js:10
subscribe @ Observable.js:23
subscribe @ index.js:41
(anonymous) @ subscribeTo.js:20
subscribeToResult @ subscribeToResult.js:7
_innerSub @ mergeMap.js:59
_tryNext @ mergeMap.js:53
_next @ mergeMap.js:36
next @ Subscriber.js:49
_complete @ defaultIfEmpty.js:25
complete @ Subscriber.js:61
_complete @ Subscriber.js:79
complete @ Subscriber.js:61
_complete @ Subscriber.js:79
complete @ Subscriber.js:61
_complete @ mergeMap.js:64
complete @ Subscriber.js:61
(anonymous) @ subscribeToArray.js:6
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
subscribe @ index.js:41
call @ mergeMap.js:21
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ filter.js:13
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ take.js:22
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ defaultIfEmpty.js:10
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ mergeMap.js:21
subscribe @ Observable.js:23
subscribe @ index.js:41
call @ map.js:16
subscribe @ Observable.js:23
subscribe @ index.js:41
(anonymous) @ subscribeTo.js:20
Show 186 more frames
index.js:124 TodosComponent #381: Error
    at Observable.subscribe (index.js:44)
    at MapOperator.call (map.js:16)
    at Observable.subscribe (Observable.js:23)
    at Observable.subscribe (index.js:41)
    at Store._subscribe (Observable.js:76)
    at Store.subscribe (Observable.js:27)
    at Store.subscribe (index.js:41)
    at MapOperator.call (map.js:16)
    at Store.subscribe (Observable.js:23)
    at Store.subscribe (index.js:41)`
>

**Comment by awerlang** [comment]
Hello

```
A bad HTTP response code (404) was received when fetching the script.
```

This part is unrelated.


Below that there's the stack traces of moments observables are created and were not yet disposed. They are styled as errors. Are you mistaking these alive subscriptions as errors in this tool? They are not, they MAY point to bugs in your own code.

There's nothing special about ngrx, it just works.

Hope this helps. If not, please state clearly what you expect to get from this tool and how it's failing.

**Comment by Pawel86400** [comment]
I'm still getting the error ` Current subscriptions (including indirect/nested): 1073` even though I  added `reportInnerSubscriptions: true`

`  
platformBrowserDynamic().bootstrapModule(AppModule)
  .then(ref => {
    track();
    window['stopProfiler'] = () => {
      ref.destroy();

      const subscribers = track(false);

      printSubscribers({
        subscribers,
        reportInnerSubscriptions: true,
      });
    };
  })


onDeactivate(component: object) {
    const subscribers = track(false);

    printSubscribers({
      subscribers,
      reportInnerSubscriptions: true,
      prefix: component.constructor.name,
      timeout: 200,
    });
  }`

**Comment by awerlang** [comment]
@Pawel86400 refer to this https://github.com/awerlang/observable-profiler/issues/1#issuecomment-521220926

If needed, open an issue.

I'll lock this issue for the time being to avoid unrelated discussions.
